# Julia 代码格式化配置
style = "blue"
indent = 4
margin = 92
always_for_in = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
import_to_using = false
pipe_to_function_call = false
short_to_long_function_def = false
long_to_short_function_def = false
always_use_return = true
annotate_untyped_fields_with_any = true
format_docstrings = true
conditional_to_if = false
normalize_line_endings = "auto"